# Generated by Django 6.0.3 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neologismo', '0003_contexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='neologismo',
            name='data_registro',
            field=models.DateTimeField(
                blank=True,
                help_text='Data e hora de registro informada na fonte dos dados',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='neologismo',
            name='elaborado_por',
            field=models.CharField(
                blank=True,
                help_text='Nome informado como elaborador na fonte dos dados',
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name='neologismo',
            name='tipologia',
            field=models.CharField(
                blank=True,
                help_text='Processo de formação do neologismo. Ex: derivação prefixal',
                max_length=100,
            ),
        ),
    ]