# Generated by Django 6.0.3 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neologismo', '0004_neologismo_csv_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contexto',
            name='link',
            field=models.URLField(blank=True, help_text='Link para a fonte original', max_length=500),
        ),
    ]