# Generated by Django 6.0.3 on 2026-09-29 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neologismo', '0005_alter_contexto_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contexto',
            options={'ordering': ['data_criacao'], 'verbose_name': 'contexto', 'verbose_name_plural': 'contextos'},
        ),
        migrations.AlterModelOptions(
            name='neologismo',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'neologismo', 'verbose_name_plural': 'neologismos'},
        ),
        migrations.AddField(
            model_name='neologismo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neologismo',
            name='moderado_em',
            field=models.DateTimeField(blank=True, help_text='Data da última decisão de moderação', null=True),
        ),
        migrations.AddField(
            model_name='neologismo',
            name='moderado_por',
            field=models.ForeignKey(blank=True, help_text='Quem tomou a última decisão de moderação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neologismos_moderados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neologismo',
            name='slug',
            field=models.SlugField(blank=True, help_text='Versão do título usada na URL. Gerada automaticamente.', max_length=70),
        ),
        migrations.AlterField(
            model_name='neologismo',
            name='contexto_uso',
            field=models.TextField(blank=True, help_text='Frase de exemplo demonstrando o uso'),
        ),
        migrations.AlterField(
            model_name='neologismo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='neologismo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=10),
        ),
        migrations.AddIndex(
            model_name='neologismo',
            index=models.Index(fields=['status', '-data_criacao'], name='neo_status_data_idx'),
        ),
    ]
